import React from 'react';
import { ToolPage } from '@/src/components/ToolPage';
import { QrCode, Download, Settings, RefreshCw } from 'lucide-react';

export const QrCodeGenerator: React.FC = () => {
  const [text, setText] = React.useState('https://tooolify.vercel.app');
  const [size, setSize] = React.useState(256);
  const [color, setColor] = React.useState('#4f46e5');
  const [bgColor, setBgColor] = React.useState('#ffffff');

  // We use a simple QR code API for the preview
  const qrUrl = `https://api.qrserver.com/v1/create-qr-code/?size=${size}x${size}&data=${encodeURIComponent(text)}&color=${color.replace('#', '')}&bgcolor=${bgColor.replace('#', '')}`;

  return (
    <ToolPage
      toolId="qr-code-generator"
      category="generator"
      title="QR Code Generator Online - Create Custom QR Codes for Free"
      description="Generate custom QR codes for URLs, text, Wi-Fi, and more instantly. Our free online QR code maker allows you to customize colors, size, and download high-resolution images for print or digital use."
      keywords={['qr code generator', 'create qr code online', 'custom qr code maker', 'qr code for url', 'free qr code generator', 'high resolution qr code', 'wifi qr code generator']}
      longDescription={`QR codes (Quick Response codes) are a versatile and powerful way to bridge the gap between the physical and digital worlds. Whether you're a business owner wanting to share your website, a marketer tracking campaign performance, or just someone wanting to share a Wi-Fi password without typing it out, our QR Code Generator is the perfect tool for you.

### Why Choose Our QR Code Maker?
Our generator is designed for simplicity and customization. We provide professional-grade features for free, directly in your browser.

- **Custom URLs & Text**: Generate codes for any website link, plain text, or contact information.
- **Full Color Customization**: Match your brand identity by choosing custom colors for both the foreground and background of your QR code.
- **High Resolution Downloads**: Get sharp, high-quality PNG images that are ready for professional printing on business cards, posters, or flyers.
- **Instant Live Preview**: See your changes in real-time as you adjust the content, size, and colors.
- **Privacy Focused**: We don't track the data you encode. Your QR codes are generated on the fly and are yours to keep.

### Common Use Cases for QR Codes:
- **Marketing Materials**: Add QR codes to flyers, brochures, and posters to drive traffic to your landing pages.
- **Business Cards**: Make it easy for people to save your contact info or visit your portfolio.
- **Restaurant Menus**: Provide a touchless menu experience for your customers.
- **Wi-Fi Sharing**: Create a QR code that lets guests join your network instantly.`}
      faqs={[
        { question: "Do the QR codes I generate expire?", answer: "No, the QR codes generated by Tooolify are static. This means they will work indefinitely as long as the URL or data you encoded remains active." },
        { question: "Can I use these QR codes for commercial purposes?", answer: "Yes! You are free to use any QR code generated on our platform for personal or commercial projects without any attribution or fees." },
        { question: "How do I ensure my QR code is scannable?", answer: "Always ensure there is high contrast between the foreground and background colors. A dark foreground on a light background is the most reliable combination for all scanners." },
        { question: "What is the best size for a printed QR code?", answer: "For business cards, a size of at least 2cm x 2cm is recommended. For larger materials like posters, ensure the code is large enough to be scanned from a distance." }
      ]}
    >
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
        <div className="space-y-6">
          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Content (URL or Text)</label>
            <input 
              type="text" 
              value={text}
              onChange={(e) => setText(e.target.value)}
              placeholder="https://example.com"
              className="w-full px-6 py-4 bg-slate-50 border border-slate-200 rounded-2xl focus:ring-2 focus:ring-indigo-500 outline-none font-medium"
            />
          </div>

          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Foreground Color</label>
              <div className="flex gap-2">
                <input 
                  type="color" 
                  value={color}
                  onChange={(e) => setColor(e.target.value)}
                  className="w-12 h-12 rounded-xl cursor-pointer border-none p-0"
                />
                <input 
                  type="text" 
                  value={color}
                  onChange={(e) => setColor(e.target.value)}
                  className="flex-1 px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-mono"
                />
              </div>
            </div>
            <div className="space-y-2">
              <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Background Color</label>
              <div className="flex gap-2">
                <input 
                  type="color" 
                  value={bgColor}
                  onChange={(e) => setBgColor(e.target.value)}
                  className="w-12 h-12 rounded-xl cursor-pointer border-none p-0"
                />
                <input 
                  type="text" 
                  value={bgColor}
                  onChange={(e) => setBgColor(e.target.value)}
                  className="flex-1 px-4 py-2 bg-slate-50 border border-slate-200 rounded-xl text-xs font-mono"
                />
              </div>
            </div>
          </div>

          <div className="space-y-2">
            <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Size (px)</label>
            <input 
              type="range" 
              min="100" 
              max="1000" 
              step="10"
              value={size}
              onChange={(e) => setSize(parseInt(e.target.value))}
              className="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-indigo-600"
            />
            <div className="text-center text-xs font-bold text-slate-400">{size} x {size}</div>
          </div>
        </div>

        <div className="flex flex-col items-center justify-center space-y-8 p-12 bg-slate-50 rounded-[48px] border border-slate-100">
          <div className="p-6 bg-white rounded-[32px] shadow-2xl shadow-indigo-500/10 border border-slate-100">
            <img 
              src={qrUrl} 
              alt="Generated QR Code" 
              className="w-full h-auto rounded-xl"
              referrerPolicy="no-referrer"
            />
          </div>
          <a 
            href={qrUrl} 
            download="qrcode.png"
            target="_blank"
            rel="noopener noreferrer"
            className="px-10 py-4 bg-slate-900 text-white font-bold rounded-2xl hover:bg-slate-800 transition-all flex items-center gap-3 shadow-xl"
          >
            <Download size={20} />
            Download PNG
          </a>
        </div>
      </div>
    </ToolPage>
  );
};
