import React from 'react';
import { SEO } from '../components/SEO';
import { motion } from 'motion/react';
import { FileText, Scale, Zap, AlertCircle } from 'lucide-react';

export const Terms: React.FC = () => {
  return (
    <div className="pb-32">
      <SEO 
        title="Terms of Service | Tooolify" 
        description="Review Tooolify's terms of service. By using our free online tools, you agree to these terms and conditions."
      />

      <div className="max-w-4xl mx-auto px-6 pt-20">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-16"
        >
          {/* Header */}
          <div className="space-y-6 text-center">
            <div className="inline-flex items-center gap-2 px-4 py-2 bg-slate-50 text-slate-600 rounded-full text-xs font-black uppercase tracking-widest">
              <FileText size={14} />
              <span>Legal Agreement</span>
            </div>
            <h1 className="text-5xl md:text-6xl font-black text-slate-900 tracking-tight font-display leading-[1.1]">
              Terms of <span className="text-indigo-600">Service</span>
            </h1>
            <p className="text-slate-500 text-lg font-medium max-w-2xl mx-auto">
              Please read these terms carefully before using our services. By accessing Tooolify, you agree to be bound by these terms.
            </p>
          </div>

          {/* Key Points */}
          <div className="grid md:grid-cols-3 gap-6">
            {[
              { icon: Zap, title: "Fair Use", desc: "Our tools are free for personal and commercial use under fair use guidelines." },
              { icon: Scale, title: "No Warranty", desc: "Tools are provided 'as is' without any express or implied warranties." },
              { icon: AlertCircle, title: "Responsibility", desc: "Users are responsible for their use of the content generated by our tools." }
            ].map((item, i) => (
              <div key={i} className="p-8 bg-white border border-slate-100 rounded-3xl space-y-4">
                <div className="w-12 h-12 bg-slate-50 rounded-2xl flex items-center justify-center text-slate-600">
                  <item.icon size={24} />
                </div>
                <h3 className="font-bold text-slate-900">{item.title}</h3>
                <p className="text-sm text-slate-500 leading-relaxed font-medium">{item.desc}</p>
              </div>
            ))}
          </div>

          {/* Main Content */}
          <div className="prose prose-slate max-w-none prose-headings:font-display prose-headings:font-black prose-headings:tracking-tight prose-p:text-slate-600 prose-p:font-medium prose-p:leading-relaxed">
            <section className="space-y-6">
              <h2 className="text-3xl text-slate-900 pt-8 border-t border-slate-100">1. Acceptance of Terms</h2>
              <p>
                By accessing and using Tooolify ("the Website"), you accept and agree to be bound by the terms and provision of this agreement. Any participation in this service will constitute acceptance of this agreement.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-3xl text-slate-900 pt-8 border-t border-slate-100">2. Description of Service</h2>
              <p>
                Tooolify provides a variety of free online utilities, AI generators, and developer tools. We reserve the right to modify or discontinue any tool or service at any time without notice. We are not liable to you or any third party should we exercise our right to modify or discontinue the service.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-3xl text-slate-900 pt-8 border-t border-slate-100">3. User Conduct</h2>
              <p>
                You agree not to use the Website to:
              </p>
              <ul className="list-disc pl-6 space-y-2 text-slate-600 font-medium">
                <li>Automate requests with scripts or bots without prior authorization.</li>
                <li>Upload malicious code, viruses, or any items of a destructive nature.</li>
                <li>Impersonate any person or entity.</li>
                <li>Engage in any activity that interferes with or disrupts the Website's functionality.</li>
              </ul>
            </section>

            <section className="space-y-6">
              <h2 className="text-3xl text-slate-900 pt-8 border-t border-slate-100">4. Disclaimer of Warranties</h2>
              <p>
                The services and all information, content, materials, and products included on or otherwise made available to you through the Website are provided on an "as is" and "as available" basis. Tooolify makes no representations or warranties of any kind, express or implied.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-3xl text-slate-900 pt-8 border-t border-slate-100">5. Limitation of Liability</h2>
              <p>
                In no event shall Tooolify be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or the inability to use our services.
              </p>
            </section>

            <section className="space-y-6">
              <h2 className="text-3xl text-slate-900 pt-8 border-t border-slate-100">6. Changes to Terms</h2>
              <p>
                We reserve the right to change these conditions from time to time as we see fit and your continued use of the site will signify your acceptance of any adjustment to these terms.
              </p>
            </section>
          </div>
        </motion.div>
      </div>
    </div>
  );
};
